# Generated by Django 5.2.2 on 2025-12-06 08:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoomType',
            fields=[
                ('chat_room_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'チャットルームタイプ',
                'verbose_name_plural': 'チャットルームタイプ',
                'db_table': 'M_ChatRoomType',
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('community_id', models.AutoField(primary_key=True, serialize=False)),
                ('community_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'コミュニティ',
                'verbose_name_plural': 'コミュニティ',
                'db_table': 'T_Community',
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('token_id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('user_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('password_hash', models.CharField(blank=True, default='', max_length=255)),
                ('is_google_auth', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'メール認証トークン',
                'verbose_name_plural': 'メール認証トークン',
                'db_table': 'T_EmailVerificationToken',
            },
        ),
        migrations.CreateModel(
            name='IdentityVerificationStatus',
            fields=[
                ('identity_verification_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': '本人確認ステータス',
                'verbose_name_plural': '本人確認ステータス',
                'db_table': 'M_IdentityVerificationStatus',
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('insurance_id', models.AutoField(primary_key=True, serialize=False)),
                ('insurance_name', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('insurance_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': '保険',
                'verbose_name_plural': '保険',
                'db_table': 'M_Insurance',
            },
        ),
        migrations.CreateModel(
            name='InsuranceEnrollmentStatus',
            fields=[
                ('insurance_enrollment_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': '保険加入ステータス',
                'verbose_name_plural': '保険加入ステータス',
                'db_table': 'M_InsuranceEnrollmentStatus',
            },
        ),
        migrations.CreateModel(
            name='MessageReadStatus',
            fields=[
                ('message_read_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'メッセージ既読ステータス',
                'verbose_name_plural': 'メッセージ既読ステータス',
                'db_table': 'M_MessageReadStatus',
            },
        ),
        migrations.CreateModel(
            name='NotificationReadStatus',
            fields=[
                ('notification_read_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': '通知既読ステータス',
                'verbose_name_plural': '通知既読ステータス',
                'db_table': 'M_NotificationReadStatus',
            },
        ),
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('notification_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_type_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': '通知タイプ',
                'verbose_name_plural': '通知タイプ',
                'db_table': 'M_NotificationType',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('payment_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_type_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': '支払い方法',
                'verbose_name_plural': '支払い方法',
                'db_table': 'M_PaymentType',
            },
        ),
        migrations.CreateModel(
            name='ProductCondition',
            fields=[
                ('product_condition_id', models.AutoField(primary_key=True, serialize=False)),
                ('condition_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': '商品状態',
                'verbose_name_plural': '商品状態',
                'db_table': 'M_ProductCondition',
            },
        ),
        migrations.CreateModel(
            name='ProductStatus',
            fields=[
                ('product_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': '商品ステータス',
                'verbose_name_plural': '商品ステータス',
                'db_table': 'M_ProductStatus',
            },
        ),
        migrations.CreateModel(
            name='RentalRequestStatus',
            fields=[
                ('rental_request_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'レンタルリクエストステータス',
                'verbose_name_plural': 'レンタルリクエストステータス',
                'db_table': 'M_RentalRequestStatus',
            },
        ),
        migrations.CreateModel(
            name='RentalStatus',
            fields=[
                ('rental_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'レンタルステータス',
                'verbose_name_plural': 'レンタルステータス',
                'db_table': 'M_RentalStatus',
            },
        ),
        migrations.CreateModel(
            name='ReportReason',
            fields=[
                ('report_reason_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_reason_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': '通報理由',
                'verbose_name_plural': '通報理由',
                'db_table': 'M_ReportReason',
            },
        ),
        migrations.CreateModel(
            name='ReturnReason',
            fields=[
                ('return_reason_id', models.AutoField(primary_key=True, serialize=False)),
                ('return_reason_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': '返却理由',
                'verbose_name_plural': '返却理由',
                'db_table': 'M_ReturnReason',
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('shipping_method_id', models.AutoField(primary_key=True, serialize=False)),
                ('shipping_method_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': '配送方法',
                'verbose_name_plural': '配送方法',
                'db_table': 'M_ShippingMethod',
            },
        ),
        migrations.CreateModel(
            name='TargetUserType',
            fields=[
                ('target_user_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'ターゲットユーザータイプ',
                'verbose_name_plural': 'ターゲットユーザータイプ',
                'db_table': 'M_TargetUserType',
            },
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('user_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'ユーザーステータス',
                'verbose_name_plural': 'ユーザーステータス',
                'db_table': 'M_UserStatus',
            },
        ),
        migrations.CreateModel(
            name='ViolationReason',
            fields=[
                ('violation_reason_id', models.AutoField(primary_key=True, serialize=False)),
                ('violation_reason_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': '違反理由',
                'verbose_name_plural': '違反理由',
                'db_table': 'M_ViolationReason',
            },
        ),
        migrations.CreateModel(
            name='ViolationStatus',
            fields=[
                ('violation_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': '違反ステータス',
                'verbose_name_plural': '違反ステータス',
                'db_table': 'M_ViolationStatus',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('password_hash', models.CharField(max_length=255)),
                ('login_attempt_count', models.IntegerField(default=0)),
                ('last_login_datetime', models.DateTimeField(blank=True, null=True)),
                ('register_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('delete_datetime', models.DateTimeField(blank=True, null=True)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('user_status', models.ForeignKey(db_column='user_status_id', on_delete=django.db.models.deletion.PROTECT, to='monotal.userstatus')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
                'db_table': 'T_User',
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('chat_room_id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_room_type', models.ForeignKey(db_column='chat_room_type_id', on_delete=django.db.models.deletion.PROTECT, to='monotal.chatroomtype')),
                ('community', models.ForeignKey(blank=True, db_column='community_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='monotal.community')),
            ],
            options={
                'verbose_name': 'チャットルーム',
                'verbose_name_plural': 'チャットルーム',
                'db_table': 'T_ChatRoom',
            },
        ),
        migrations.CreateModel(
            name='IdentityVerification',
            fields=[
                ('identity_verification_id', models.AutoField(primary_key=True, serialize=False)),
                ('rejection_datetime', models.DateTimeField(blank=True, null=True)),
                ('approval_datetime', models.DateTimeField(blank=True, null=True)),
                ('register_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('identity_verification_status', models.ForeignKey(db_column='identity_verification_status_id', on_delete=django.db.models.deletion.PROTECT, to='monotal.identityverificationstatus')),
            ],
            options={
                'verbose_name': '本人確認',
                'verbose_name_plural': '本人確認',
                'db_table': 'T_IdentityVerification',
            },
        ),
        migrations.CreateModel(
            name='IdentityVerificationImage',
            fields=[
                ('identity_verification_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_data', models.BinaryField()),
                ('register_datetime', models.DateTimeField(auto_now_add=True)),
                ('identity_verification', models.ForeignKey(db_column='identity_verification_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='monotal.identityverification')),
            ],
            options={
                'verbose_name': '本人確認画像',
                'verbose_name_plural': '本人確認画像',
                'db_table': 'T_IdentityVerificationImage',
            },
        ),
        migrations.CreateModel(
            name='InsuranceEnrollment',
            fields=[
                ('insurance_enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('insurance_start_datetime', models.DateTimeField()),
                ('insurance_end_datetime', models.DateTimeField()),
                ('insurance', models.ForeignKey(db_column='insurance_id', on_delete=django.db.models.deletion.PROTECT, to='monotal.insurance')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '保険加入',
                'verbose_name_plural': '保険加入',
                'db_table': 'T_InsuranceEnrollment',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_content', models.CharField(blank=True, max_length=2000, null=True)),
                ('register_datetime', models.DateTimeField(auto_now_add=True)),
                ('chat_room', models.ForeignKey(db_column='chat_room_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='monotal.chatroom')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'メッセージ',
                'verbose_name_plural': 'メッセージ',
                'db_table': 'T_Message',
            },
        ),
        migrations.CreateModel(
            name='MessageImage',
            fields=[
                ('message_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_data', models.BinaryField()),
                ('register_datetime', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(db_column='message_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='monotal.message')),
            ],
            options={
                'verbose_name': 'メッセージ画像',
                'verbose_name_plural': 'メッセージ画像',
                'db_table': 'T_MessageImage',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_title', models.CharField(max_length=200)),
                ('notification_detail', models.CharField(blank=True, max_length=1000, null=True)),
                ('link_url', models.CharField(blank=True, max_length=500, null=True)),
                ('notification_type', models.ForeignKey(db_column='notification_type_id', on_delete=django.db.models.deletion.PROTECT, to='monotal.notificationtype')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'T_Notification',
            },
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('payment_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('transfer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('card_token', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to=settings.AUTH_USER_MODEL)),
                ('payment_type', models.ForeignKey(db_column='payment_type_id', on_delete=django.db.models.deletion.PROTECT, to='monotal.paymenttype')),
            ],
            options={
                'verbose_name': '支払い情報',
                'verbose_name_plural': '支払い情報',
                'db_table': 'T_PaymentInfo',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('rental_days', models.IntegerField()),
                ('rental_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contract_datetime', models.DateTimeField(blank=True, null=True)),
                ('listing_stop_datetime', models.DateTimeField(blank=True, null=True)),
                ('register_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('delete_datetime', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'T_Product',
            },
        ),
        migrations.AddField(
            model_name='chatroom',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='monotal.product'),
        ),
        migrations.CreateModel(
            name='BrowsingHistory',
            fields=[
                ('browsing_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('register_datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='browsing_history', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='monotal.product')),
            ],
            options={
                'verbose_name': '閲覧履歴',
                'verbose_name_plural': '閲覧履歴',
                'db_table': 'T_BrowsingHistory',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('product_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('parent_product_category', models.ForeignKey(blank=True, db_column='parent_product_category_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='monotal.productcategory')),
            ],
            options={
                'verbose_name': '商品カテゴリ',
                'verbose_name_plural': '商品カテゴリ',
                'db_table': 'M_ProductCategory',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(db_column='product_category_id', on_delete=django.db.models.deletion.PROTECT, to='monotal.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_condition',
            field=models.ForeignKey(db_column='product_condition_id', on_delete=django.db.models.deletion.PROTECT, to='monotal.productcondition'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_status',
            field=models.ForeignKey(db_column='product_status_id', on_delete=django.db.models.deletion.PROTECT, to='monotal.productstatus'),
        ),
        migrations.CreateModel(
            name='RentalRequest',
            fields=[
                ('rental_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('approval_datetime', models.DateTimeField(blank=True, null=True)),
                ('rejection_datetime', models.DateTimeField(blank=True, null=True)),
                ('register_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, to='monotal.product')),
                ('requested_user', models.ForeignKey(db_column='requested_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests_received', to=settings.AUTH_USER_MODEL)),
                ('requester_user', models.ForeignKey(db_column='requester_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests_made', to=settings.AUTH_USER_MODEL)),
                ('rental_request_status', models.ForeignKey(db_column='rental_request_status_id', on_delete=django.db.models.deletion.PROTECT, to='monotal.rentalrequeststatus')),
            ],
            options={
                'verbose_name': 'レンタルリクエスト',
                'verbose_name_plural': 'レンタルリクエスト',
                'db_table': 'T_RentalRequest',
            },
        ),
        migrations.CreateModel(
            name='RentalHistory',
            fields=[
                ('rental_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('shipping_completed_datetime', models.DateTimeField(blank=True, null=True)),
                ('rental_start_datetime', models.DateTimeField(blank=True, null=True)),
                ('rental_end_datetime', models.DateTimeField(blank=True, null=True)),
                ('receipt_completed_datetime', models.DateTimeField(blank=True, null=True)),
                ('register_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('lender_user', models.ForeignKey(db_column='lender_user_id', on_delete=django.db.models.deletion.PROTECT, related_name='rentals_as_lender', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, to='monotal.product')),
                ('renter_user', models.ForeignKey(db_column='renter_user_id', on_delete=django.db.models.deletion.PROTECT, related_name='rentals_as_renter', to=settings.AUTH_USER_MODEL)),
                ('rental_status', models.ForeignKey(db_column='rental_status_id', on_delete=django.db.models.deletion.PROTECT, to='monotal.rentalstatus')),
            ],
            options={
                'verbose_name': 'レンタル履歴',
                'verbose_name_plural': 'レンタル履歴',
                'db_table': 'T_RentalHistory',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_detail', models.CharField(blank=True, max_length=1000, null=True)),
                ('report_datetime', models.DateTimeField()),
                ('register_datetime', models.DateTimeField(auto_now_add=True)),
                ('reporter_user', models.ForeignKey(db_column='reporter_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('report_reason', models.ForeignKey(db_column='report_reason_id', on_delete=django.db.models.deletion.PROTECT, to='monotal.reportreason')),
            ],
            options={
                'verbose_name': '通報',
                'verbose_name_plural': '通報',
                'db_table': 'T_Report',
            },
        ),
        migrations.CreateModel(
            name='ReturnReasonHistory',
            fields=[
                ('return_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('return_request_datetime', models.DateTimeField()),
                ('return_completed_datetime', models.DateTimeField(blank=True, null=True)),
                ('return_reason_detail', models.CharField(blank=True, max_length=1000, null=True)),
                ('return_status_id', models.IntegerField(blank=True, null=True)),
                ('register_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('rental_history', models.ForeignKey(db_column='rental_history_id', on_delete=django.db.models.deletion.CASCADE, to='monotal.rentalhistory')),
                ('return_reason', models.ForeignKey(db_column='return_reason_id', on_delete=django.db.models.deletion.PROTECT, to='monotal.returnreason')),
            ],
            options={
                'verbose_name': '返却理由履歴',
                'verbose_name_plural': '返却理由履歴',
                'db_table': 'T_ReturnReason',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_method',
            field=models.ForeignKey(db_column='shipping_method_id', on_delete=django.db.models.deletion.PROTECT, to='monotal.shippingmethod'),
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('user_address_id', models.AutoField(primary_key=True, serialize=False)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('street_address', models.CharField(blank=True, max_length=200, null=True)),
                ('building_name', models.CharField(blank=True, max_length=100, null=True)),
                ('register_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ユーザー住所',
                'verbose_name_plural': 'ユーザー住所',
                'db_table': 'UserAddress',
            },
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('user_review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_content', models.CharField(blank=True, max_length=1000, null=True)),
                ('review_score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('register_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('reviewed_user', models.ForeignKey(db_column='reviewed_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer_user', models.ForeignKey(db_column='reviewer_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ユーザー評価',
                'verbose_name_plural': 'ユーザー評価',
                'db_table': 'T_UserReview',
            },
        ),
        migrations.CreateModel(
            name='ViolationHistory',
            fields=[
                ('violation_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('violation_detail', models.CharField(blank=True, max_length=1000, null=True)),
                ('violation_release_datetime', models.DateTimeField(blank=True, null=True)),
                ('register_datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='violations', to=settings.AUTH_USER_MODEL)),
                ('violation_reason', models.ForeignKey(db_column='violation_reason_id', on_delete=django.db.models.deletion.PROTECT, to='monotal.violationreason')),
                ('violation_status', models.ForeignKey(db_column='violation_status_id', on_delete=django.db.models.deletion.PROTECT, to='monotal.violationstatus')),
            ],
            options={
                'verbose_name': '違反履歴',
                'verbose_name_plural': '違反履歴',
                'db_table': 'T_ViolationHistory',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('block_id', models.AutoField(primary_key=True, serialize=False)),
                ('register_datetime', models.DateTimeField(auto_now_add=True)),
                ('blocked_user', models.ForeignKey(db_column='blocked_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('blocker_user', models.ForeignKey(db_column='blocker_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='blocking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ブロック',
                'verbose_name_plural': 'ブロック',
                'db_table': 'T_Block',
                'unique_together': {('blocker_user', 'blocked_user')},
            },
        ),
        migrations.CreateModel(
            name='ChatRoomParticipant',
            fields=[
                ('chat_room_participant_id', models.AutoField(primary_key=True, serialize=False)),
                ('register_datetime', models.DateTimeField(auto_now_add=True)),
                ('chat_room', models.ForeignKey(db_column='chat_room_id', on_delete=django.db.models.deletion.CASCADE, to='monotal.chatroom')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'チャットルーム参加者',
                'verbose_name_plural': 'チャットルーム参加者',
                'db_table': 'T_ChatRoomParticipant',
                'unique_together': {('chat_room', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('follow_id', models.AutoField(primary_key=True, serialize=False)),
                ('register_datetime', models.DateTimeField(auto_now_add=True)),
                ('followed_user', models.ForeignKey(db_column='followed_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('follower_user', models.ForeignKey(db_column='follower_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'フォロー',
                'verbose_name_plural': 'フォロー',
                'db_table': 'T_Follow',
                'unique_together': {('follower_user', 'followed_user')},
            },
        ),
        migrations.CreateModel(
            name='MessageRead',
            fields=[
                ('message_read_id', models.AutoField(primary_key=True, serialize=False)),
                ('read_datetime', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(db_column='message_id', on_delete=django.db.models.deletion.CASCADE, to='monotal.message')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('message_read_status', models.ForeignKey(db_column='message_read_status_id', on_delete=django.db.models.deletion.PROTECT, to='monotal.messagereadstatus')),
            ],
            options={
                'verbose_name': 'メッセージ既読',
                'verbose_name_plural': 'メッセージ既読',
                'db_table': 'T_MessageRead',
                'unique_together': {('message', 'user')},
            },
        ),
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('notification_read_id', models.AutoField(primary_key=True, serialize=False)),
                ('read_datetime', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(db_column='notification_id', on_delete=django.db.models.deletion.CASCADE, to='monotal.notification')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('notification_read_status', models.ForeignKey(db_column='notification_read_status_id', on_delete=django.db.models.deletion.PROTECT, to='monotal.notificationreadstatus')),
            ],
            options={
                'verbose_name': '通知既読',
                'verbose_name_plural': '通知既読',
                'db_table': 'T_NotificationRead',
                'unique_together': {('notification', 'user')},
            },
        ),
        migrations.CreateModel(
            name='NotificationTargetUser',
            fields=[
                ('notification_target_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('register_datetime', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(db_column='notification_id', on_delete=django.db.models.deletion.CASCADE, to='monotal.notification')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '通知ターゲットユーザー',
                'verbose_name_plural': '通知ターゲットユーザー',
                'db_table': 'T_NotificationTargetUser',
                'unique_together': {('notification', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('bookmark_id', models.AutoField(primary_key=True, serialize=False)),
                ('register_datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='monotal.product')),
            ],
            options={
                'verbose_name': 'お気に入り',
                'verbose_name_plural': 'お気に入り',
                'db_table': 'T_Bookmark',
                'unique_together': {('product', 'user')},
            },
        ),
    ]
