# Generated by Django 5.2.2 on 2025-11-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名')),
                ('image', models.ImageField(upload_to='products/', verbose_name='商品画像')),
                ('description', models.TextField(verbose_name='商品詳細')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品価格')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['-created_at'],
            },
        ),
    ]
