# Generated by Django 5.2.2 on 2025-12-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
