# Generated by Django 5.2.2 on 2025-12-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0001_initial'),
    ]

    operations = [
        # bio field is already in 0001_initial
    ]
