# Generated by Django 5.2.2 on 2025-12-08 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0002_user_bio'),
    ]

    operations = [
        # UserHobby is already in 0001_initial
    ]
