# Generated by Django 5.2.2 on 2025-12-08 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0002_user_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHobby',
            fields=[
                ('user_hobby_id', models.AutoField(primary_key=True, serialize=False)),
                ('register_datetime', models.DateTimeField(auto_now_add=True)),
                ('product_category', models.ForeignKey(db_column='product_category_id', on_delete=django.db.models.deletion.CASCADE, to='monotal.productcategory')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ユーザー趣味',
                'verbose_name_plural': 'ユーザー趣味',
                'db_table': 'T_UserHobby',
                'unique_together': {('user', 'product_category')},
            },
        ),
    ]
