# Generated by Django 5.2.2 on 2026-01-20 07:53

import django.db.models.deletion
from django.db import migrations, models


def populate_shipping_burden(apps, schema_editor):
    """発送料負担マスターデータを投入"""
    ShippingBurden = apps.get_model('monotal', 'ShippingBurden')
    burdens = [
        {'shipping_burden_id': 1, 'burden_name': '出品者負担'},
        {'shipping_burden_id': 2, 'burden_name': 'レンタル者負担'},
    ]
    for burden in burdens:
        ShippingBurden.objects.get_or_create(
            shipping_burden_id=burden['shipping_burden_id'],
            defaults={'burden_name': burden['burden_name']}
        )


def reverse_populate_shipping_burden(apps, schema_editor):
    """マスターデータを削除（ロールバック用）"""
    ShippingBurden = apps.get_model('monotal', 'ShippingBurden')
    ShippingBurden.objects.filter(shipping_burden_id__in=[1, 2]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0002_populate_master_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingBurden',
            fields=[
                ('shipping_burden_id', models.AutoField(primary_key=True, serialize=False)),
                ('burden_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': '発送料負担',
                'verbose_name_plural': '発送料負担',
                'db_table': 'M_ShippingBurden',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_burden',
            field=models.ForeignKey(blank=True, db_column='shipping_burden_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='monotal.shippingburden'),
        ),
        migrations.RunPython(populate_shipping_burden, reverse_populate_shipping_burden),
    ]
