# Generated by Django 5.2.2 on 2026-01-20 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0002_populate_master_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingBurden',
            fields=[
                ('shipping_burden_id', models.AutoField(primary_key=True, serialize=False)),
                ('burden_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': '発送料負担',
                'verbose_name_plural': '発送料負担',
                'db_table': 'M_ShippingBurden',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_burden',
            field=models.ForeignKey(blank=True, db_column='shipping_burden_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='monotal.shippingburden'),
        ),
    ]
