# Generated by Django 5.2.2 on 2025-12-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0002_user_phone_number_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
