# Generated by Django 5.2.2 on 2026-01-14 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0003_userhobby'),
    ]

    operations = [
        # ProductImage is already in 0001_initial
    ]
