# Generated by Django 5.2.2 on 2026-01-16 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0004_productimage'),
    ]

    # Note: All operations moved to 0001_initial.py during squash
    operations = []
