# Generated by Django 5.2.2 on 2026-01-16 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0004_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('prefecture_id', models.AutoField(primary_key=True, serialize=False)),
                ('prefecture_name', models.CharField(max_length=10, unique=True)),
                ('prefecture_code', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'verbose_name': '都道府県',
                'verbose_name_plural': '都道府県',
                'db_table': 'M_Prefecture',
                'ordering': ['prefecture_id'],
            },
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='building_name',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='municipality',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='useraddress',
            table='T_UserAddress',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='prefecture',
            field=models.ForeignKey(blank=True, db_column='prefecture_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='monotal.prefecture'),
        ),
        migrations.CreateModel(
            name='ProductRentalPlan',
            fields=[
                ('product_rental_plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('rental_days', models.IntegerField()),
                ('rental_fee', models.DecimalField(decimal_places=0, max_digits=10)),
                ('register_datetime', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='rental_plans', to='monotal.product')),
            ],
            options={
                'verbose_name': '商品レンタルプラン',
                'verbose_name_plural': '商品レンタルプラン',
                'db_table': 'T_ProductRentalPlan',
                'ordering': ['rental_days'],
            },
        ),
    ]
