# Generated by Django 5.2.2 on 2026-01-16 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0006_populate_prefectures'),
    ]

    operations = [
        # ShippingDays model and Product.shipping_days field are already in 0001_initial
    ]
