# Generated by Django 5.2.2 on 2026-01-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0009_useraddress_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shipping_method',
        ),
        migrations.DeleteModel(
            name='ShippingMethod',
        ),
    ]
