# Generated by Django 5.2.2 on 2026-01-26 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0010_remove_product_shipping_method_delete_shippingmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryImage',
            fields=[
                ('product_category_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('register_datetime', models.DateTimeField(auto_now_add=True)),
                ('product_category', models.OneToOneField(db_column='product_category_id', on_delete=django.db.models.deletion.CASCADE, related_name='image', to='monotal.productcategory')),
            ],
            options={
                'verbose_name': '商品カテゴリ画像',
                'verbose_name_plural': '商品カテゴリ画像',
                'db_table': 'T_ProductCategoryImage',
            },
        ),
    ]
