# Generated by Django 5.2.2

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0010_bankaccount'),
        ('monotal', '0011_productcategoryimage'),
    ]

    operations = [
    ]
