# Generated by Django 5.2.2 on 2026-01-30 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0012_merge_20260130'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('credit_card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_number_last4', models.CharField(max_length=4)),
                ('expiry_month', models.IntegerField()),
                ('expiry_year', models.IntegerField()),
                ('card_holder_name', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('register_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'クレジットカード',
                'verbose_name_plural': 'クレジットカード',
                'db_table': 'T_CreditCard',
            },
        ),
    ]
