# Generated by Django 5.2.2 on 2026-02-03 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0013_creditcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPersonalInfo',
            fields=[
                ('user_personal_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50, verbose_name='姓')),
                ('first_name', models.CharField(max_length=50, verbose_name='名')),
                ('last_name_kana', models.CharField(blank=True, max_length=50, null=True, verbose_name='姓（カナ）')),
                ('first_name_kana', models.CharField(blank=True, max_length=50, null=True, verbose_name='名（カナ）')),
                ('birth_date', models.DateField(verbose_name='生年月日')),
                ('gender', models.IntegerField(choices=[(1, '男性'), (2, '女性'), (3, 'その他')], verbose_name='性別')),
                ('register_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ユーザー個人情報',
                'verbose_name_plural': 'ユーザー個人情報',
                'db_table': 'T_UserPersonalInfo',
            },
        ),
    ]
