# Generated by Django 5.2.2 on 2026-02-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0014_add_user_personal_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityverification',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='生年月日'),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='名'),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='first_name_kana',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='名（カナ）'),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, '男性'), (2, '女性'), (3, 'その他')], null=True, verbose_name='性別'),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='姓'),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='last_name_kana',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='姓（カナ）'),
        ),
    ]
