# Generated by Django 5.2.2 on 2026-02-03 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0015_add_personal_info_to_identity_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_address',
            field=models.ForeignKey(blank=True, db_column='shipping_address_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_as_shipping', to='monotal.useraddress'),
        ),
    ]
