# Generated by Django 5.2.2 on 2026-02-03 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0016_add_shipping_address_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalhistory',
            name='renter_address',
            field=models.ForeignKey(blank=True, db_column='renter_address_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rental_histories_as_renter', to='monotal.useraddress'),
        ),
    ]
