# Generated by Django 5.2.2 on 2026-02-03 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0017_add_renter_address_to_rental_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='rental_history',
            field=models.ForeignKey(blank=True, db_column='rental_history_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='monotal.rentalhistory'),
        ),
    ]
