# Generated by Django 5.2.2 on 2026-02-03 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0018_add_rental_history_to_chatroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalRequestReadType',
            fields=[
                ('rental_request_read_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'レンタル申請既読タイプ',
                'verbose_name_plural': 'レンタル申請既読タイプ',
                'db_table': 'M_RentalRequestReadType',
            },
        ),
        migrations.CreateModel(
            name='RentalRequestRead',
            fields=[
                ('rental_request_read_id', models.AutoField(primary_key=True, serialize=False)),
                ('read_datetime', models.DateTimeField(auto_now_add=True)),
                ('rental_request', models.ForeignKey(db_column='rental_request_id', on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='monotal.rentalrequest')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rental_request_read_type', models.ForeignKey(db_column='rental_request_read_type_id', on_delete=django.db.models.deletion.PROTECT, to='monotal.rentalrequestreadtype')),
            ],
            options={
                'verbose_name': 'レンタル申請既読',
                'verbose_name_plural': 'レンタル申請既読',
                'db_table': 'T_RentalRequestRead',
                'unique_together': {('rental_request', 'user', 'rental_request_read_type')},
            },
        ),
    ]
