# Generated by Django 5.2.2 on 2026-02-04 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0019_add_rental_request_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_prefecture',
            field=models.ForeignKey(blank=True, db_column='shipping_prefecture_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_as_shipping', to='monotal.prefecture'),
        ),
    ]
