# Generated by Django 5.2.2 on 2026-02-09 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0021_update_rental_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceClaimStatus',
            fields=[
                ('insurance_claim_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': '保険クレームステータス',
                'verbose_name_plural': '保険クレームステータス',
                'db_table': 'M_InsuranceClaimStatus',
            },
        ),
        migrations.AddField(
            model_name='insurance',
            name='coverage_limit',
            field=models.DecimalField(decimal_places=0, default=50000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='insuranceenrollment',
            name='insurance_end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('claim_id', models.AutoField(primary_key=True, serialize=False)),
                ('claim_description', models.TextField()),
                ('repair_cost', models.DecimalField(decimal_places=0, max_digits=10)),
                ('claim_datetime', models.DateTimeField(auto_now_add=True)),
                ('approval_datetime', models.DateTimeField(blank=True, null=True)),
                ('rejection_datetime', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, to='monotal.product')),
                ('rental_history', models.ForeignKey(blank=True, db_column='rental_history_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='monotal.rentalhistory')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('insurance_claim_status', models.ForeignKey(db_column='insurance_claim_status_id', on_delete=django.db.models.deletion.PROTECT, to='monotal.insuranceclaimstatus')),
            ],
            options={
                'verbose_name': '保険クレーム',
                'verbose_name_plural': '保険クレーム',
                'db_table': 'T_InsuranceClaim',
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaimImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='insurance_claims/')),
                ('image_type', models.IntegerField(choices=[(1, '破損画像'), (2, '領収書'), (3, '修理後画像')])),
                ('register_datetime', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(db_column='claim_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='monotal.insuranceclaim')),
            ],
            options={
                'verbose_name': '保険クレーム画像',
                'verbose_name_plural': '保険クレーム画像',
                'db_table': 'T_InsuranceClaimImage',
            },
        ),
    ]
