# Generated by Django 5.2.2 on 2026-02-13 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0022_insuranceclaimstatus_insurance_coverage_limit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insuranceclaim',
            options={'verbose_name': '補償申請', 'verbose_name_plural': '補償申請'},
        ),
        migrations.AlterModelOptions(
            name='insuranceclaimimage',
            options={'verbose_name': '補償申請画像', 'verbose_name_plural': '補償申請画像'},
        ),
        migrations.AlterModelOptions(
            name='insuranceclaimstatus',
            options={'verbose_name': '補償申請ステータス', 'verbose_name_plural': '補償申請ステータス'},
        ),
        migrations.CreateModel(
            name='InsuranceCoveragePeriod',
            fields=[
                ('coverage_period_id', models.AutoField(primary_key=True, serialize=False)),
                ('period_start_datetime', models.DateTimeField()),
                ('period_end_datetime', models.DateTimeField()),
                ('coverage_limit', models.DecimalField(decimal_places=0, max_digits=10)),
                ('used_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('insurance_enrollment', models.OneToOneField(db_column='insurance_enrollment_id', on_delete=django.db.models.deletion.CASCADE, related_name='coverage_period', to='monotal.insuranceenrollment')),
            ],
            options={
                'verbose_name': '補償残枠管理',
                'verbose_name_plural': '補償残枠管理',
                'db_table': 'T_InsuranceCoveragePeriod',
            },
        ),
    ]
