# Generated by Django 5.2.2 on 2026-02-13 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0023_alter_insuranceclaim_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceenrollment',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='insuranceenrollment',
            name='insurance_enrollment_status',
            field=models.ForeignKey(db_column='insurance_enrollment_status_id', default=2, on_delete=django.db.models.deletion.PROTECT, to='monotal.insuranceenrollmentstatus'),
        ),
    ]
