# Generated by Django 5.2.2 on 2026-02-14 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0024_insuranceenrollment_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='rental_history',
            field=models.ForeignKey(blank=True, db_column='rental_history_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='monotal.rentalhistory'),
        ),
        migrations.AlterUniqueTogether(
            name='userreview',
            unique_together={('reviewer_user', 'rental_history')},
        ),
    ]
