# Generated by Django 5.2.2 on 2026-02-14 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0025_userreview_rental_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalhistory',
            name='overdue_notified_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalhistory',
            name='rental_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalhistory',
            name='rental_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalhistory',
            name='return_carrier_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rentalhistory',
            name='return_shipping_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalhistory',
            name='return_tracking_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rentalhistory',
            name='shipping_carrier_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rentalhistory',
            name='shipping_tracking_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='product_rental_plan',
            field=models.ForeignKey(blank=True, db_column='product_rental_plan_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rental_requests', to='monotal.productrentalplan'),
        ),
    ]
