# Generated by Django 5.2.2 on 2026-02-18 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0028_report_reported_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingNotification',
            fields=[
                ('listing_notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('register_datetime', models.DateTimeField(auto_now_add=True)),
                ('subscriber_user', models.ForeignKey(db_column='subscriber_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='listing_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(db_column='target_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='listing_subscribers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '出品通知購読',
                'verbose_name_plural': '出品通知購読',
                'db_table': 'T_ListingNotification',
                'unique_together': {('subscriber_user', 'target_user')},
            },
        ),
    ]
