# Generated by Django 5.2.2 on 2026-02-18 08:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0029_listingnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='カテゴリ名')),
            ],
            options={
                'verbose_name': '掲示板カテゴリ',
                'verbose_name_plural': '掲示板カテゴリ',
                'db_table': 'M_BoardCategory',
            },
        ),
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name': 'コミュニティ（掲示板）', 'verbose_name_plural': 'コミュニティ（掲示板）'},
        ),
        migrations.RemoveField(
            model_name='community',
            name='community_name',
        ),
        migrations.AddField(
            model_name='community',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時'),
        ),
        migrations.AddField(
            model_name='community',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_communities', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AddField(
            model_name='community',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='説明文'),
        ),
        migrations.AddField(
            model_name='community',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='掲示板タイトル'),
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/', verbose_name='添付画像'),
        ),
        migrations.AddField(
            model_name='message',
            name='product_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monotal.product', verbose_name='商品リンク'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monotal.boardcategory', verbose_name='カテゴリ'),
        ),
    ]
