# Generated by Django 5.2.2 on 2026-02-19 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def insert_qa_status(apps, schema_editor):
    QAStatus = apps.get_model('monotal', 'QAStatus')
    QAStatus.objects.bulk_create([
        QAStatus(id=1, name='受付中'),
        QAStatus(id=2, name='解決済み'),
        QAStatus(id=3, name='期限切れ終了'),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0031_add_community_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='QACategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='カテゴリ名')),
            ],
            options={
                'verbose_name': 'Q&Aカテゴリ',
                'verbose_name_plural': 'Q&Aカテゴリ',
                'db_table': 'M_QACategory',
            },
        ),
        migrations.CreateModel(
            name='QAStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='ステータス名')),
            ],
            options={
                'verbose_name': 'Q&Aステータス',
                'verbose_name_plural': 'Q&Aステータス',
                'db_table': 'M_QAStatus',
            },
        ),
        migrations.CreateModel(
            name='QAQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='本文')),
                ('expires_at', models.DateTimeField(verbose_name='回答受付期限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='monotal.qacategory', verbose_name='カテゴリ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_questions', to=settings.AUTH_USER_MODEL, verbose_name='質問者')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='monotal.qastatus', verbose_name='ステータス')),
            ],
            options={
                'verbose_name': 'Q&A質問',
                'verbose_name_plural': 'Q&A質問',
                'db_table': 'T_QAQuestion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(insert_qa_status, migrations.RunPython.noop),
        migrations.CreateModel(
            name='QAAnswer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='回答内容')),
                ('is_best_answer', models.BooleanField(default=False, verbose_name='ベストアンサー')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('parent_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='monotal.qaanswer', verbose_name='親回答')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_answers', to=settings.AUTH_USER_MODEL, verbose_name='回答者')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='monotal.qaquestion', verbose_name='質問')),
            ],
            options={
                'verbose_name': 'Q&A回答',
                'verbose_name_plural': 'Q&A回答',
                'db_table': 'T_QAAnswer',
                'ordering': ['created_at'],
            },
        ),
    ]
