# Generated by Django 5.2.2 on 2026-02-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0033_add_community_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
