# Generated by Django 5.2.2 on 2026-02-22 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0033_add_community_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='monotal.message', verbose_name='返信元メッセージ'),
        ),
    ]
