# Generated by Django 5.2.2 on 2026-02-22 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0035_cancellation_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('coupon_id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon_name', models.CharField(max_length=200, verbose_name='クーポン名')),
                ('discount_amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='値引き額')),
                ('expires_at', models.DateTimeField(verbose_name='有効期限')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効フラグ')),
                ('abolished_datetime', models.DateTimeField(blank=True, null=True, verbose_name='廃止日時')),
                ('register_datetime', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'クーポン',
                'verbose_name_plural': 'クーポン',
                'db_table': 'M_Coupon',
            },
        ),
        migrations.AddField(
            model_name='qaquestion',
            name='expiry_notified_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='期限前通知日時'),
        ),
        migrations.AddField(
            model_name='rentalhistory',
            name='coupon_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='クーポン値引き額'),
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('user_coupon_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_possessed', models.BooleanField(default=True, verbose_name='所持フラグ')),
                ('used_datetime', models.DateTimeField(blank=True, null=True, verbose_name='使用日時')),
                ('register_datetime', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('coupon', models.ForeignKey(db_column='coupon_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to='monotal.coupon', verbose_name='クーポン')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザー所持クーポン',
                'verbose_name_plural': 'ユーザー所持クーポン',
                'db_table': 'T_UserCoupon',
            },
        ),
        migrations.AddField(
            model_name='rentalhistory',
            name='user_coupon',
            field=models.ForeignKey(blank=True, db_column='user_coupon_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_histories', to='monotal.usercoupon', verbose_name='使用クーポン'),
        ),
        migrations.CreateModel(
            name='CouponTargetCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon', models.ForeignKey(db_column='coupon_id', on_delete=django.db.models.deletion.CASCADE, related_name='target_categories', to='monotal.coupon', verbose_name='クーポン')),
                ('product_category', models.ForeignKey(db_column='product_category_id', on_delete=django.db.models.deletion.CASCADE, related_name='coupon_targets', to='monotal.productcategory', verbose_name='対象カテゴリ')),
            ],
            options={
                'verbose_name': 'クーポン対象カテゴリ',
                'verbose_name_plural': 'クーポン対象カテゴリ',
                'db_table': 'M_CouponTargetCategory',
                'unique_together': {('coupon', 'product_category')},
            },
        ),
    ]
