# Generated by Django 5.2.2 on 2026-02-22 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0036_coupon_qaquestion_expiry_notified_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('quest_id', models.AutoField(primary_key=True, serialize=False)),
                ('quest_name', models.CharField(max_length=200, verbose_name='クエスト名')),
                ('quest_description', models.CharField(max_length=500, verbose_name='クエスト説明')),
                ('difficulty', models.IntegerField(choices=[(0, 'チュートリアル'), (1, '初級'), (2, '中級'), (3, '上級')], default=0, verbose_name='難易度')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効フラグ')),
                ('register_datetime', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('product_category', models.ForeignKey(blank=True, db_column='product_category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quests', to='monotal.productcategory', verbose_name='商品カテゴリ')),
                ('reward_coupon', models.ForeignKey(blank=True, db_column='reward_coupon_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quests', to='monotal.coupon', verbose_name='報酬クーポン')),
            ],
            options={
                'verbose_name': 'クエスト',
                'verbose_name_plural': 'クエスト',
                'db_table': 'M_Quest',
                'ordering': ['display_order', 'quest_id'],
            },
        ),
        migrations.CreateModel(
            name='QuestMission',
            fields=[
                ('quest_mission_id', models.AutoField(primary_key=True, serialize=False)),
                ('mission_name', models.CharField(max_length=200, verbose_name='ミッション名')),
                ('mission_description', models.CharField(blank=True, default='', max_length=500, verbose_name='ミッション説明')),
                ('condition_type', models.CharField(max_length=50, verbose_name='条件種別')),
                ('condition_params', models.JSONField(default=dict, verbose_name='条件パラメータ')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('quest', models.ForeignKey(db_column='quest_id', on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='monotal.quest', verbose_name='クエスト')),
            ],
            options={
                'verbose_name': 'クエストミッション',
                'verbose_name_plural': 'クエストミッション',
                'db_table': 'M_QuestMission',
                'ordering': ['display_order', 'quest_mission_id'],
            },
        ),
        migrations.CreateModel(
            name='UserCompletedQuest',
            fields=[
                ('user_completed_quest_id', models.AutoField(primary_key=True, serialize=False)),
                ('completed_datetime', models.DateTimeField(verbose_name='完了日時')),
                ('reward_claimed', models.BooleanField(default=False, verbose_name='報酬受取済み')),
                ('reward_claimed_datetime', models.DateTimeField(blank=True, null=True, verbose_name='報酬受取日時')),
                ('register_datetime', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('quest', models.ForeignKey(db_column='quest_id', on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='monotal.quest', verbose_name='クエスト')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='completed_quests', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザークエスト完了',
                'verbose_name_plural': 'ユーザークエスト完了',
                'db_table': 'T_UserCompletedQuest',
                'unique_together': {('user', 'quest')},
            },
        ),
    ]
