# Generated by Django 5.2.2 on 2026-02-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0037_quest_questmission_usercompletedquest'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='有効期限'),
        ),
    ]
