# Generated by Django 5.2.2 on 2026-02-22 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0034_message_reply_to'),
        ('monotal', '0038_quest_expires_at'),
    ]

    operations = [
    ]
