# Generated by Django 5.2.2 on 2026-03-04 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monotal', '0041_populate_insurance_claim_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_condition',
            field=models.ForeignKey(blank=True, db_column='product_condition_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='monotal.productcondition'),
        ),
    ]
